version: 1.0.{build} 
shallow_clone: true
clone_folder: c:\projects\pol_testing
init:
- git config --global core.autocrlf true
install:
- cd lib
- time /T
- prepare_boost.bat > NUL
- time /T
- cd ..
cache: lib/boost_1_55_0
build_script:
- msbuild "pol-core/pol-2013.sln" /verbosity:normal /p:Configuration=Release /p:Platform="x64" /m:2
#test: off
test_script: 
- c:\\Python34\\python.exe testsuite\\escript\\performtests.py pol-core\\ecompile\\Release\\x64\\ecompile.exe pol-core\\runecl\\Release\\x64\\runecl.exe -n 5
deploy: off
